import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Frontend Mentor Challenges</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.png' />
      </Head>
      <main className='flex items-center justify-center w-screen h-screen'>
        <h1 className='font-bold text-red-600 text-9xl'>Hello World</h1>
      </main>
    </>
  );
}
